[package]
name = "mcp-server"
version = "0.1.0"
edition = "2024"

[dependencies]
mcp-core = { path = "../mcp-core" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
unknown = { path = "../unknown" }
