[package]
name = "mcp-server-app"
version = "0.1.0"
edition = "2024"

[dependencies]
mcp-server = {path = "../mcp-server"}
mcp-server-macro = {path = "../mcp-server-macro"}
mcp-core = {path = "../mcp-core"}
unknown = {path = "../unknown"}
